### ISSUE TITLE
Update to 1.7.1 to Support for large meshes

### ISSUE THREAD

**Issue by inkydragon** [Gnimuc/CImGui.jl#8]
ref: [ImDrawList: Support for large meshes (64k+ vertices) with 16-bits indices · Issue #2591 · ocornut/imgui](https://github.com/ocornut/imgui/issues/2591)

When I'm trying to draw some [Fractals](https://github.com/inkydragon/Jui.jl/blob/Fractal-demo/test/Fractals.jl), It's easy to touch this limit.

**Comment by Gnimuc** [comment]
Hi, do you wanna make a PR? It should be as simple as to upgrade CImGuiBuilder to 1.71 and then regenerate wrappers using Clang.jl. I don't have time to do this until Sep. 15.(sorry, I'm quite addicted to WoW Classic.)

**Comment by Gnimuc** [comment]
Hi @inkydragon, I just pushed 1.72b to master. Sorry for the postpone, it took me another week to level up my priest to 60. :P

**Comment by inkydragon** [comment]
There must be something wrong. When `VtxBuffer.Size` > `2^16`, imgui still crashed. (use CImGui v1.72.0)

```
Assertion failed!

Program: C:\Users\woclass\AppData\Local\Julia-1.0.4\bin\julia.exe
File: /workspace/srcdir/cimgui/imgui/imgui.cpp, Line4030

Expression: draw_list->_VtxCurrentIdx < (1<<16) && "Too many vertices in ImDrawList using 6-bit indices. Read comment above"
```

![image](https://user-images.githubusercontent.com/5158738/66299459-2af15980-e926-11e9-9937-594c598f7445.png)

Julia test code: [Jui.jl/LargeMeshTest.jl](https://github.com/inkydragon/Jui.jl/blob/Fractal-demo/test/LargeMeshTest.jl#L52)

imgui test code: [examples/example_glfw_opengl3 @ 1.72b](https://github.com/ocornut/imgui/tree/6a0d0dab5a9f0b9518a2bc9bb456a69895ae0962/examples/example_glfw_opengl3) + [code snippet Issue #2591](https://github.com/ocornut/imgui/issues/2591#issuecomment-496954460)

**Comment by Gnimuc** [comment]
Oops, I forgot to update the backend, could you give #12 a try? @inkydragon
